name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -S ${{github.workspace}}
      
    - name: Build
      run: cmake --build ${{github.workspace}}/build
      
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ./students_db_test
