name: C/C++ CI with GoogleTest

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libgtest-dev
        
    - name: Build GoogleTest
      run: |
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
        sudo cp lib/*.a /usr/lib
        
    - name: Compile program
      run: |
        g++ -std=c++20 -pthread -lgtest -lgtest_main main.cpp -o program.out
        
    - name: Run tests
      run: |
        ./program.out --test
        
    - name: Test normal execution
      run: |
        # Автоматически вводим '0' для выхода
        echo "0" | timeout 5s ./program.out || true
        echo "Normal execution test completed"
