name: C/C++ CI with GoogleTest

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install GoogleTest
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libgtest-dev cmake
        
    - name: Build GoogleTest manually
      run: |
        cd /usr/src/gtest
        sudo mkdir -p build
        cd build
        sudo cmake ..
        sudo make
        sudo make install
        
    - name: Compile program
      run: |
        g++ -std=c++20 -pthread -lgtest -lgtest_main main.cpp -o program.out
        
    - name: Run tests
      run: |
        ./program.out --test
