name: C/C++ CI with GoogleTest

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake git
        
    - name: Clone and build GoogleTest locally
      run: |
        # Клонируем и собираем GoogleTest в текущей директории
        git clone https://github.com/google/googletest.git
        cd googletest
        mkdir build
        cd build
        cmake ..
        make -j4
        
    - name: Compile with local GoogleTest
      run: |
        # Компилируем с локальными библиотеками
        g++ -std=c++20 -pthread -Igoogletest/googletest/include -Lgoogletest/build/lib main.cpp -lgtest -lgtest_main -o program.out
        ./program.out --test
