name: C/C++ CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libgtest-dev libgtest-main
        
    - name: Build and Test
      run: |
        g++ -std=c++11 -lgtest -lgtest_main -pthread -o students_db_test main.cpp
        ./students_db_test --gtest_output=xml:test_results.xml
      
    - name: Show test results
      run: |
        echo "Тесты завершены. Проверьте вывод выше."
