name: C/C++ CI with Google Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
    
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -S ${{github.workspace}}
      
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release
      
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: |
        ./students_db_test
        ctest --output-on-failure
